# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/sbase/sbcontrol
# Target is a library:  

TARGETDEPS += ../../../src/sbase/sbqapital/libsbqapital.a
LIBS += ../../../src/sbase/sbqapital/libsbqapital.a
INCLUDEPATH = ../../../src/sbase/sbqapital
MOC_DIR = .moc
OBJECTS_DIR = .obj
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
