# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/client/packages
# Target is a library:  

HEADERS += cconnectpackage.h \
           cchatpackage.h 
SOURCES += cconnectpackage.cpp \
           cchatpackage.cpp 
QT += xml
KDEV_QTVER = 4
INCLUDEPATH += ../../../src/dlib/dgui \
../../../src/dlib/dcore
MOC_DIR = .moc
UI_DIR = .ui
OBJECTS_DIR = .obj
CONFIG += release \
warn_on \
staticlib
TEMPLATE = lib
