# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/qpscontrol
# Target is a library:  

TEMPLATE = lib 
CONFIG += release \
          warn_on \
          staticlib 
OBJECTS_DIR = .obj 
MOC_DIR = .moc 
