# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./sbase/sbqpserver
# Target is a library:  

TEMPLATE = lib 
CONFIG += release \
          warn_on \
          staticlib 
OBJECTS_DIR = .obj 
MOC_DIR = .moc 
SOURCES += sberror.cpp \
           sblogger.cpp 
HEADERS += sberror.h \
           sblogger.h \
           sbqpserver.h 
