# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/client
# Target is a subdirs project 

SUBDIRS += dlslib \
	   shell 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
