# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/client/modules
# Target is a subdirs project 

SUBDIRS += clients \
           help 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
