# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/server
# Target is a subdirs project 

INSTALLS += data 
data.files += data/* 
data.path = /data/ 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
SUBDIRS += packages \
	   shell
