# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += qpsred \
           qpsbd \
           qpslogica \
           qpscontrol \
           qpserver 
TEMPLATE = subdirs 
CONFIG += release \
          warn_on 
TARGET = ../bin/qpserver 
