# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += 3rdparty \
	   src 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
