######################################################################
# Automatically generated by qmake (1.07a) Sat Aug 21 14:06:18 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += qpinstalador.h
SOURCES += qpinstalador.cpp
IMAGES += ../artwork/presentacion.png
