# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/client/themes
# Target is a library:  

INSTALLS += default 
default.files += default 
default.path = /data/themes/ 
KDEV_QTVER = 4 
INCLUDEPATH += ../../dlib/ 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = subdirs
