# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/sbase/sbqapital
# Target is a library:  

MOC_DIR = .moc 
OBJECTS_DIR = .obj 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += sbqapital.h \
           sberror.h \
           sblogger.h 
SOURCES += sberror.cpp \
           sblogger.cpp 
