# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/qpadmin
# Target is a subdirs project 

CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
SUBDIRS += qpared \
           qpagui \
           qpalogica \
           qpadmin 
