# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./sbase/sbqpack
# Target is a library:  

MOC_DIR = .moc 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += sberror.h \
           sblogger.h \
           sbqpack.h 
SOURCES += sberror.cpp \
           sblogger.cpp 
