# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/dartlib
# Target is a subdirs project 

SUBDIRS += dcore \
	   dgui
KDEV_QTVER = 4 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
