# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/sbase/sbbd
# Target is a library:  

MOC_DIR = .moc 
OBJECTS_DIR = .obj 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += sbbdconexion.h \
           sbbd.h 
SOURCES += sbbdconexion.cpp 
