# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += sbase \
           src 
TEMPLATE = subdirs 
CONFIG += release \
          warn_on 
