# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./sbase/sbcontrol
# Target is a library:  

INCLUDEPATH = ../../sbase/sbqpack 
MOC_DIR = .moc 
OBJECTS_DIR = .obj 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
