# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/qpcliente
# Target is a subdirs project 

CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
SUBDIRS += qpcred \
           qpcgui \
           qpclogica \
           qpcliente 
