# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/sbase
# Target is a subdirs project 

INCLUDEPATH = /home/krawek/qapital/src/sbase/red/ \
              /home/krawek/qapital/src/sbase/logica/ \
              /home/krawek/qapital/src/sbase/gui/ \
              /home/krawek/qapital/src/sbase/control/ \
              /home/krawek/qapital/src/sbase/bd/ 
CONFIG += debug \
          warn_on 
TEMPLATE = subdirs 
SUBDIRS += sbqapital \
           sbxml \
           sbgui \
           sbred \
           sblogica \
           sbcontrol \
           sbbd 
