# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += dlib \
           dtserver \
           client \
           formdesigner 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
