# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SUBDIRS += dartlib \
	   server \
           client
KDEV_QTVER = 3 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
