# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./sbase
# Target is a subdirs project 

TEMPLATE = subdirs 
CONFIG += release \
          warn_on 
SUBDIRS += sbbd \
           sbcontrol \
           sblogica \
           sbxml \
           sbred \
           sbqpserver 
