# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/client/modules/agend
# Target is a library:  

QT += xml 
KDEV_QTVER = 4 
INCLUDEPATH += ../../../../src/client/lib \
               ../../../../src/dlib/dgui \
               ../../../../src/dlib/dcore 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
HEADERS += cagendmodulewidget.h 
SOURCES += cagendmodulewidget.cpp 
