# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/client/lib
# Target is a library:  

HEADERS += global.h 
KDEV_QTVER = 4 
CONFIG += release \
          warn_on \
          staticlib 
TEMPLATE = lib 
